---
# Items that apply to ALL profiles:
# spring:
#   profiles: default
# server:
#   port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://imsf:Welcome2!Imsf@localhost:8010/eureka/

# ---
# spring:
#   profiles: primary
#   application:
#     name: eureka-server-clustered
# server:
#   port: 8011

# eureka:
#   client:
#     registerWithEureka: true
#     fetchRegistry: true
#     serviceUrl:
#       defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

# ---
# spring:
#   profiles: secondary
#   application:
#     name: eureka-server-clustered
# server:
#   port: 8012

# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#     serviceUrl:
#       defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/

# ---
# spring:
#   profiles: tertiary
#   application:
#     name: eureka-server-clustered
# server:
#   port: 8013

# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: true
#     serviceUrl:
#       defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: this

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: apple

---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

